  name: Deploy to Shared Hosting
  on:
    push:
      branches:
        - main
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 20.x
        - name: Install dependencies
          run: yarn install
        - name: Build
          run: yarn build
        - name: Deploy
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: ./out/
            server-dir: /dnculture.biz.id/
            exclude: .git*